### ISSUE TITLE
Problems with getting data into VS extension

### ISSUE THREAD

**Issue by kamrann** [Viladoman/CompileScore#1] opened 2020-08-23 17:07 UTC
So I think there are perhaps a couple of different issues. I loaded up the test project (built as-is with Clang 10) one further time, and without having changed anything this time it correctly displayed the data (I'd previously rebuilt the project and restarted VS a couple of times without any luck, despite the parsing reporting success). So I guess maybe there's just some unpredictability relating to VS extension initialization order? If it was possible to enable more logging it might help pin down things like that.

As for my own project, built using a source-built pre-Clang 11, I'm still seeing the source files displayed but with no numbers. Attaching an example json file from the Clang output - I can see one additional field that didn't show up in the test project output, but it doesn't look like that would be an issue. Otherwise the format appears the same, but I may be missing something.
![no_data](https://user-images.githubusercontent.com/2475657/90984174-4760a980-e56b-11ea-88c1-2515a8f66011.png)
[api_alloc.cpp.json.zip](https://github.com/Viladoman/CompileScore/files/5114434/api_alloc.cpp.json.zip)

**Comment by Viladoman** [comment] 2020-08-23 20:52
Thanks for giving the sample json as I don't have Clang 11 locally. I could pinpoint a couple of issues in the extractor.js ( I was assuming tid 0 and also the event 'thread_name' was messing around the data ). This ended up into not loading any event at all. I already submitted the fixes for the DataExporter and it should work now. 

About the plugin issue: I still have to investigate it.

FYI, The folders for the dataextractor and TestProject changed a bit but everything should still be working ( I am starting a c++ data extractor option ). 

Let me know if the issue got fixed.

**Comment by kamrann** [comment] 2020-08-24 13:36
Yep, getting data on my project now, thanks! Going to take me a fair while to understand how to interpret it all, but this looks great.

A couple of other things, I'll just note here rather than opening individual issues:
- If I rerun the node command that updates the .scor file while the solution is open, it seems to crash the instance of VS.
- Defaulting first click on column header to sort descending would make sense I think
- The text filter doesn't seem to work on the Includes tab
- Long template names are getting cut short. Would be useful to be able to see the full name via a tooltip, unless it's Clang's output that is cutting them off?

Let me know if I can help with any more info/testing.

**Comment by Viladoman** [comment] 2020-08-24 20:04
Thanks, I really appreciate your help and it actually helps me find issues faster. 

- I have a fix for the crash. It happened when the .scor file is big so the 'filechanged' event was triggered while the script was still writing into the file. 
- I agree, I have it on my TODO list. 
- I am having a hard time reproducing this one. I had it once, so the issue is present, but I have been unable to see it again since then. ( if you have consistent way to force this state I would love to know it )  
- I agree. The limit is manually placed by me at the exporter level ( it is there to avoid big names to make the .scor file size explode in big projects), but I can add some flags to the exporter to opt-in. 

Let me know if updating the extension to v1.2.4 fixed the crashes.

**Comment by kamrann** [comment] 2020-08-26 18:03
Yep, those issues seem to be sorted now!

**Comment by Viladoman** [comment] 2020-08-27 20:38
I am glad to hear that. Thanks for the help. I will close this issue and move the remaining suggestions to the TODO list.

**Closed by Viladoman** 2020-08-27 20:38 UTC
